Models/ErrorViewModel.cs
namespace GarageApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CarAdminController.cs
using GarageApp.Data;
using GarageApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace GarageApp.Controllers
{
    public class CarAdminController : Controller
    {
        private ApplicationDbContext _context;
        
        public CarAdminController(
            IWebHostEnvironment environment,
            ApplicationDbContext context)
        {
            this.Environment = environment;

            this._context = context;
        }


        public IActionResult Index()
        {
            var cars = _context.Cars.ToList();
            return View(cars);
        }

        public async Task<IActionResult> Details(string? LicensePlate)
        {
            if (LicensePlate == null)
            {
                return RedirectToAction("Index");
            }

            var cars = await _context.Cars
                .FirstOrDefaultAsync(m => m.LicensePlate == LicensePlate);
            if (cars == null)
            {
                return RedirectToAction("Index");
            }

            return View(cars);

        }

        [HttpPost]
        public async Task<IActionResult> EditAsync(Car car)
        {
            var existingCar = await _context.Cars.FindAsync(car.LicensePlate);
            existingCar.Brand = car.Brand;
            existingCar.Odometer = car.Odometer;
            existingCar.SalesPrice = car.SalesPrice;

            await _context.SaveChangesAsync();

            return RedirectToAction("Index");

        }

        private IWebHostEnvironment Environment;

    

        [HttpPost]
        public async Task<IActionResult> UploadFile(string licensePlate, IFormFile file)

        {
            if (licensePlate == null)
            {
                return NotFound();
            }
            else if (!_context.Cars.Any(c => c.LicensePlate == licensePlate))
            {
                return NotFound();
            }
            else
            {

                var carImagePath = Path.Join(
                Environment.WebRootPath, "Cars", licensePlate, "Images"
                    );

                if (!Directory.Exists(carImagePath))
                {
                    Directory.CreateDirectory(carImagePath);
                }

                if (file != null)
                {
                    var filePath = Path.Join(carImagePath, file.FileName);
                    using (var stream = System.IO.File.Create(filePath))
                    {
                        await file.CopyToAsync(stream);
                    }

                }

                return Ok();
            }


        }
    }
}

Controllers/CarController.cs
using GarageApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GarageApp.Controllers{
    public class CarController : Controller
    {
        private ApplicationDbContext _context;

        public CarController(ApplicationDbContext context) {
            this._context = context;
        }

        public IActionResult Index(string? brand)
        {
            var cars = _context.Cars.AsQueryable();


            if (brand != null)
            {
                cars = cars.Where(c => c.Brand == brand);
            }

            var result = cars.ToList();


            return View(result);
        }

        public async Task<IActionResult> Details(string licensePlate)
        {

            var cars = await _context.Cars
                .FirstOrDefaultAsync(m => m.LicensePlate == licensePlate);
            if (cars == null)
            {
                return NotFound();
            }

            return View(cars);
        }




    }
}

Controllers/HomeController.cs
using GarageApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GarageApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {

            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Car/Index.cshtml
@using GarageApp.Data
@model List<Car>

@{
    ViewData["Title"] = "Cards";
}

        <div class="uk-section uk-section-default">
            <div class="uk-container uk-container-medium">
                <h1 class="uk-text-bolder na-text-color uk-margin-small na-animate-charcter">C A R S</h1><hr>
                <div id="searchForm">
                    @inject ApplicationDbContext dbContext;
                    <form onchange="submit()">
                        <div class="uk-grid-match uk-child-width-1-4@m" uk-grid>
                            <div class="uk-margin">
                                <label>Brands</label>
                                <select class="uk-select" name="brand">
                                    <option value=""></option>
                                    @foreach(var brand in dbContext.Cars.Select(c=> c.Brand).Distinct().ToList())
                                    {
                                        <option>@brand</option>
                                    }
                                </select>
                            </div>

                            <div class="uk-margin">
                                <label>LicensePlate</label>
                                <select class="uk-select" name="LicensePlate">
                                    <option value=""></option>
                                    @foreach(var LicensePlate in dbContext.Cars.Select(c=> c.LicensePlate).Distinct().ToList())
                                    {
                                        <option>@LicensePlate</option>
                                    }
                                </select>
                            </div>

                            <div class="uk-margin">
                                <label>Odometer</label>
                                <select class="uk-select">
                                    <option value=""></option>
                                    @foreach(var Odometer in dbContext.Cars.Select(c=> c.Odometer).Distinct().ToList())
                                    {
                                        <option>@Odometer</option>
                                    }
                                </select>
                            </div>
                        
                            <div class="uk-margin">
                                <label>SalesPrice</label>
                                <select class="uk-select" name="SalesPrice">
                                    <option value=""></option>
                                    @foreach(var SalesPrice in dbContext.Cars.Select(c=> c.SalesPrice).Distinct().ToList())
                                    {
                                        <option>@SalesPrice</option>
                                    }
                                </select>
                            </div>
                         </div>
                    </form>

                </div><hr>

                <div class="uk-grid-match uk-child-width-1-3@m" uk-grid>
                    @foreach(var car in Model)
                    {
                    <div class="uk-section uk-section-muted">
                        <article class="uk-comment">
                            <header class="uk-comment-header">
                                <div class="uk-grid-medium uk-flex-middle" uk-grid>
                                    <div class="uk-width-auto">
                                        <img class="uk-comment-avatar" src="@car.ImageFileName" width="80" height="80" alt="">
                                    </div>
                                    <div class="uk-width-expand">
                                        <h5 class="uk-text-lead uk-text-bold na-text-color uk-text-uppercase">@car.Brand</h5>
                                    </div>
                                </div>
                            </header>
                            <div class="uk-comment-body">
                                <div class="uk-grid-match uk-child-width-1-3@m" uk-grid>
                                    <p>@car.LicensePlate</p>
                                    <p>KM @car.Odometer</p>
                                    <p>$ @car.SalesPrice</p>
                                </div>
                            </div>
                        </article>
                    </div>
                     }
                </div>
            </div>
        </div>

Views/CarAdmin/Details.cshtml
@using GarageApp.Data
@model Car

@{ 
   ViewBag.Title = $"Edit {Model.LicensePlate}"; 
} 


<div class="uk-section uk-section-default">
    <div class="uk-container">

        <h3>Edit @Model.LicensePlate</h3>

        <form asp-action="Edit" method="post" > 
            <fieldset class="uk-fieldset">
                
                <input hidden asp-for="LicensePlate" />
                
                <div class="uk-margin">
                    <label asp-for = "Brand"></label> 
                    <input asp-for = "Brand" class="uk-input" type="text">
                    <span asp-validation-for="Brand" class="uk-text-danger"></span>
                </div>

                <div class="uk-margin">
                    <label asp-for = "Odometer"></label> 
                    <input asp-for = "Odometer" class="uk-input" type="text">
                    <span asp-validation-for="Odometer" class="uk-text-danger"></span>
                </div>


                <div class="uk-margin">
                    <label asp-for = "SalesPrice"></label> 
                    <input asp-for = "SalesPrice" class="uk-input" type="text">
                    <span asp-validation-for="SalesPrice" class="uk-text-danger"></span>
                </div>

                <header class="uk-comment-header">
                    <div class="uk-grid-medium uk-flex-middle" uk-grid>
                        <div class="uk-width-auto">
                            <img class="uk-comment-avatar" src="@Model.ImageFileName" width="100" height="0" alt="">
                        </div>
                        <div class="uk-width-expand">

                            <div class="js-upload uk-placeholder uk-text-center">
                                <span uk-icon="icon: cloud-upload"></span>
                                <span class="uk-text-middle">Upload a image</span>
                                <div uk-form-custom>
                                    <input type="file" multiple>
                                    <span class="uk-link">selecting one</span>
                                </div>
                            </div>                                    
                        </div>
                        <progress id="js-progressbar" class="uk-progress" value="0" max="100" hidden></progress>
                    </div>
                </header>

            </fieldset>
            <div> 
                <input class="uk-button uk-button-default" type = "submit" value = "Save" /> 
            </div> 
        </form>
    </div>
</div>
@{
    var fileUploadUrl = @Url.Action("UploadFile", new {licensePlate = Model.LicensePlate});
}

<script>

    var bar = document.getElementById('js-progressbar');

    UIkit.upload('.js-upload', {

        url: '@fileUploadUrl',
        allow : '*.(jpg|jpeg|gif|png)',
        multiple: true,

        beforeSend: function () {
            console.log('beforeSend', arguments);
        },
        beforeAll: function () {
            console.log('beforeAll', arguments);
        },
        load: function () {
            console.log('load', arguments);
        },
        error: function () {
            console.log('error', arguments);

        },
        complete: function () {
            console.log('complete', arguments);
        },

        loadStart: function (e) {
            console.log('loadStart', arguments);

            bar.removeAttribute('hidden');
            bar.max = e.total;
            bar.value = e.loaded;
        },

        progress: function (e) {
            console.log('progress', arguments);

            bar.max = e.total;
            bar.value = e.loaded;
        },

        loadEnd: function (e) {
            console.log('loadEnd', arguments);

            bar.max = e.total;
            bar.value = e.loaded;
        },

        completeAll: function () {
            console.log('completeAll', arguments);

            setTimeout(function () {
                bar.setAttribute('hidden', 'hidden');
            }, 1000);

            alert('Upload Completed');
        }

    });

</script>

Views/CarAdmin/Index.cshtml
@using GarageApp.Data
@model List<Car>

@{
    ViewData["Title"] = "Admin Page";
}

 <div class="uk-container uk-margin-xlarge-top">
   <div class="uk-grid-match uk-child-width-1-2@m" uk-grid>
        <h1>Details</h1>
        <h1 class="uk-text-right">New</h1>
    </div></br>
    <div>
        <table>
          <tr>
            <th>LicensePlate</th>
            <th>Brand</th>
            <th>Odometer</th>
            <th>SalesPrice</th>
          </tr>
        @foreach(var car in Model)
        {
          <tr>
            <td>@car.LicensePlate</td>
            <td>@car.Brand</td>
            <td>@car.Odometer</td>
            <td>@car.SalesPrice</td>
            <td><a asp-controller="CarAdmin" asp-action="Details" asp-route-licensePlate="@car.LicensePlate">Edit</a></td>
          </tr>
         }
        </table>

    </div>
</div>
<style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }

    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }

    tr:nth-child(even) {
      background-color: #dddddd;
}
</style>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GarageApp</title>
    <link href="~/lib/uikit/css/uikit.css" type="text/css" rel="stylesheet"/>
    <script src="~/lib/uikit/js/uikit.js"></script>
</head>
<body>
    <header>
        <partial name="_Navbar"></partial>
     
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - GarageApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Navbar.cshtml
        @using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<div class="na-navbar page-header-navbar uk-background-default" uk-sticky>
            <div class="uk-container uk-container-expand uk-height-1-1">
                <nav class="uk-height-1-1" uk-navbar>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="uk-flex uk-flex-middle">
                        <h4>logo</h4>
                    </a>
                    <ul class="uk-navbar-nav uk-navbar-center uk-visible@l">
                        <li class="na-nabar-link">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="na-nabar-link">
                            <a class="nav-link text-dark" asp-controller="Car" asp-action="Index">Cars</a>
                        </li>

                        <li class="na-nabar-link">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <div class="uk-navbar-right">
                            @if (SignInManager.IsSignedIn(User))
                            {
                                //<a  class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @User.Identity?.Name!</a>
                            <a class="nav-link text-dark" asp-controller="CarAdmin" asp-action="Index">Admin</a>
                                <form  class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                    <button  type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                                </form>
                            }
                            else
                            {

                           //   <a class="uk-link-muted" asp-area="Identity" asp-page="/Account/Register">Register</a>
                                <a class="uk-link-muted" asp-area="Identity" asp-page="/Account/Login">Login</a>

                            }
                     


                    </div>
                </nav>
            </div>
          
        </div>


        
        <style>
        
        
        .page-header-navbar .uk-navbar-nav > li > a,
        .page-header-navbar .uk-icon-link,
        .page-header-navbar .uk-icon-link:hover {
            color: #001455;
        }
        .page-header-navbar .uk-navbar-nav > li > a {
            padding: 0 25px;
        }
        .page-header-navbar .multi .uk-navbar-dropdown {
              padding: 0 25px;
        }
        .page-header-navbar [class*="uk-column-"] > li {
              padding: 25px 0;
        }
        .page-header-navbar [class*="uk-column-"] > li:not(:last-child) {
              border-right: 1px solid #E5E5E5;
        }
        .offcanvas .uk-nav-header {
              color: rgba(246, 247, 249, 0.5);
        }
        .offcanvas .top-menu > li + li {
              margin-top: 10px;
        }
        .offcanvas .sub-menu {
              border-left: 1px solid #484848;
        }
        .offcanvas .sub-menu li {
              padding-left: 30px;
        }
        .offcanvas .sub-menu li.uk-nav-header {
              padding-left: 10px;
        }

        
        </style>